import { h } from './createElement.js'

/**
 * @param {string} name
 */
export function defineElement(name) {
  /**
   * @param {Props} props
   * @param {Children} children
   */
  return function createElement(props = {}, children = []) {
    return h(name, props, children)
  }
}

export const A = defineElement('a')
export const Article = defineElement('article')
export const Aside = defineElement('aside')
export const Audio = defineElement('audio')
export const B = defineElement('b')
export const Base = defineElement('base')
export const Bdi = defineElement('bdi')
export const Bdo = defineElement('bdo')
export const Blockquote = defineElement('blockquote')
export const Body = defineElement('body')
export const Br = defineElement('br')
export const Button = defineElement('button')
export const Canvas = defineElement('canvas')
export const Caption = defineElement('caption')
export const Cite = defineElement('cite')
export const Code = defineElement('code')
export const Col = defineElement('col')
export const Colgroup = defineElement('colgroup')
export const Data = defineElement('data')
export const Datalist = defineElement('datalist')
export const Dd = defineElement('dd')
export const Del = defineElement('del')
export const Details = defineElement('details')
export const Dfn = defineElement('dfn')
export const Dialog = defineElement('dialog')
export const Div = defineElement('div')
export const Dl = defineElement('dl')
export const Dt = defineElement('dt')
export const Em = defineElement('em')
export const Embed = defineElement('embed')
export const Fieldset = defineElement('fieldset')
export const Figcaption = defineElement('figcaption')
export const Figure = defineElement('figure')
export const Footer = defineElement('footer')
export const Form = defineElement('form')
export const H1 = defineElement('h1')
export const H2 = defineElement('h2')
export const H3 = defineElement('h3')
export const H4 = defineElement('h4')
export const H5 = defineElement('h5')
export const H6 = defineElement('h6')
export const Head = defineElement('head')
export const Header = defineElement('header')
export const Hgroup = defineElement('hgroup')
export const Hr = defineElement('hr')
export const I = defineElement('i')
export const Iframe = defineElement('iframe')
export const Img = defineElement('img')
export const Input = defineElement('input')
export const Ins = defineElement('ins')
export const Kbd = defineElement('kbd')
export const Label = defineElement('label')
export const Legend = defineElement('legend')
export const Li = defineElement('li')
export const Link = defineElement('link')
export const Main = defineElement('main')
export const Map = defineElement('map')
export const Mark = defineElement('mark')
export const Menu = defineElement('menu')
export const Menuitem = defineElement('menuitem')
export const Meta = defineElement('meta')
export const Meter = defineElement('meter')
export const Nav = defineElement('nav')
export const Noscript = defineElement('noscript')
export const Object = defineElement('object')
export const Ol = defineElement('ol')
export const Optgroup = defineElement('optgroup')
export const Option = defineElement('option')
export const Output = defineElement('output')
export const P = defineElement('p')
export const Param = defineElement('param')
export const Picture = defineElement('picture')
export const Pre = defineElement('pre')
export const Progress = defineElement('progress')
export const Q = defineElement('q')
export const Rp = defineElement('rp')
export const Rt = defineElement('rt')
export const Rtc = defineElement('rtc')
export const Ruby = defineElement('ruby')
export const S = defineElement('s')
export const Samp = defineElement('samp')
export const Script = defineElement('script')
export const Section = defineElement('section')
export const Select = defineElement('select')
export const Slot = defineElement('slot')
export const Small = defineElement('small')
export const Source = defineElement('source')
export const Span = defineElement('span')
export const Strong = defineElement('strong')
export const Style = defineElement('style')
export const Sub = defineElement('sub')
export const Summary = defineElement('summary')
export const Sup = defineElement('sup')
export const Tbody = defineElement('tbody')
export const Td = defineElement('td')
export const Template = defineElement('template')
export const Textarea = defineElement('textarea')
export const Tfoot = defineElement('tfoot')
export const Th = defineElement('th')
export const Thead = defineElement('thead')
export const Time = defineElement('time')
export const Title = defineElement('title')
export const Tr = defineElement('tr')
export const Track = defineElement('track')
export const U = defineElement('u')
export const Ul = defineElement('ul')
export const Var = defineElement('varEl')
export const Video = defineElement('video')
export const Wbr = defineElement('wbr')
